eclipse-tractusx/industry-core-hub

AUTHORS.md

Added myself to AUTHORS.md - like discussed.

chore: updated AUTHORS.md

---

DEPENDENCIES_IC-BACKEND
DEPENDENCIES_TX_DATASPACE_SDK
DEPENDENCIES_TX_INDUSTRY_SDK
ichub-backend/requirements.txt
tractusx_sdk/dataspace/requirements.txt
tractusx_sdk/industry/requirements.txt

There is a new PR #34 where unit tests have been added by @CDiezRodriguez 
Since he is not a committer yet and the one of the dependencies needed review, I created the PR so we can wait for it to be solved.
- Added two new dependencies `pytest` and `httpx` in all the requirements
- Runned the IP checks with review

PR #34 - IP Check

---

AUTHORS.md

Following participation requirements from the guide ...

doc: Update AUTHORS.md adding inakipaz

---

.github/workflows/verify.yml

Improve the MD file license search and include additional file types.
To ensure all licenses are properly accounted for and visible, and to address the issue mentioned here: https://github.com/eclipse-tractusx/industry-core-hub/pull/46#issuecomment-2674442975
Closes #63

feat: Update the verify workflow

---

docs/umbrella/minimal-values.yaml
docs/umbrella/postman/ic-hub-aas-registry-v3.postman_collection.json
docs/umbrella/umbrella-deployment-guide.md

It provides a guide to deploy the required tractus-x components to test the industry-core-hub using the Umbrella helm chart.
It also provides a postman collection pre-configured with guide values. More postman collections can be added.
#81

Docs: Guide to deploy Umbrella locally to test ichub

---

ichub-frontend/src/App.css
ichub-frontend/src/components/general/Header.tsx
ichub-frontend/src/components/general/JsonViewerDialog.tsx
ichub-frontend/src/components/general/Sidebar.tsx
ichub-frontend/src/pages/ProductsDetails.tsx
ichub-frontend/src/pages/ProductsList.tsx
ichub-frontend/src/tests/payloads/sidebar-elements.json

Code refactored to pass the quality gate of Sonar Cloud.
- Changes on the css file with duplicated and overrided styles.
- Rmoval of unused imports.
- Variable definition change.
- Creation of a test playload data file (`ichub-frontend/src/tests/payloads/sidebar-elements.json`) to store sidebar menu links data, so we solve the duplicated lines problem of Sonar.

fix: refactoring to pass QG from Sonar Cloud

---

charts/industry-core-hub/Chart.yaml
charts/industry-core-hub/README.md
charts/industry-core-hub/values-int.yaml
charts/industry-core-hub/values.yaml

As samuel isn't available this week, this PR is after #95 and adds the recommendations from the PR
@matbmoser i have set two paths to the vault to set email and password.
```
email: <path:industry-core-hub/data/pgadmin#email>
password: <path:industry-core-hub/data/pgadmin#password>
```

chore: add recommendations from #95 to pgadmin

---

charts/industry-core-hub/Chart.yaml
charts/industry-core-hub/values.yaml

Configured pgadmin as chart dependency to deploy along with industry core hub. 
Used portal helm chart as reference: https://github.com/eclipse-tractusx/portal/blob/main/charts/portal/values.yaml
Issue: https://github.com/eclipse-tractusx/industry-core-hub/issues/79

feat: configure pgadmin as chart dependency to deploy along with ic-hub

---

ichub-backend/models/metadata_database/__init__.py
ichub-backend/models/metadata_database/models.py
ichub-backend/models/services/__init__.py
ichub-backend/models/services/part_management.py
ichub-backend/models/services/partner_management.py
ichub-backend/models/services/twin_management.py

This contains sqlmodel based model classes for the metadata database as well as pydantic based model classes for the service layer (API layer).

feat: Added models for metadata database and service layer

---

ichub-backend/managers/metadata_database/__init__.py
ichub-backend/managers/metadata_database/manager.py
ichub-backend/managers/metadata_database/repositories.py

Added repository classes and manager classes for dealing with the persistence layer.
It depends on PR #156.

feat: Add manager for the database persistence layer

---

ichub-backend/controllers/fastapi/app.py
ichub-backend/services/partner_management_service.py

- Removed the parameter from the query and moved it to the request body.
- Refactored some methods to use `bpnl` instead of `name`.
- Added tags to controllers to enable grouping in Swagger.
To improve security and enhance API documentation clarity.

chore: Improve controller security and readability

---

ichub-backend/models/metadata_database/models.py
ichub-backend/runtimes/fastapi/main.py

Add a missing space and remove EDCService, as it is no longer in use.
It's an error.

fix: correct indentation and import errors

---

charts/industry-core-hub/Chart.yaml
charts/industry-core-hub/values-int.yaml
charts/industry-core-hub/values.yaml

Change the default storageClass value to "standard".
The current "default" value prevents Kubernetes from being deployed locally.
Closes #213

fix: Enable option for local Kubernetes deployment

---

docs/database/Metadata-DDL.sql
ichub-backend/managers/submodels/submodel_document_generator.py
ichub-backend/models/metadata_database/models.py
ichub-backend/models/services/part_management.py
ichub-backend/services/part_management_service.py
ichub-backend/services/part_sharing_shortcut_service.py
ichub-backend/services/twin_management_service.py

In order to fulfil basic fronted requirements we need to add a "name" column to the catalog part. Also we can leverage this for rendering PartTypeInformation and other product related aspect documents.

feat: Add "name" attribute to Catalog Part

---

ichub-backend/controllers/fastapi/app.py
ichub-backend/managers/metadata_database/repositories.py
ichub-backend/models/metadata_database/models.py
ichub-backend/models/services/part_management.py
ichub-backend/services/part_management_service.py
ichub-backend/services/part_sharing_shortcut_service.py
ichub-backend/services/twin_management_service.py

Added new fields to CatalogPart: status, materials, height, width, length, and weight.
Implemented logic to calculate status based on db state
Introduced typed Pydantic/SQLModel classes for Material and Measurement.
Refactored object construction to use **kwargs where possible, eliminating manual value assignments.
Added missing index=True flags to foreign-key and frequently queried fields in the models.
Required fields for frontend
To be merged after #224

Feat: Adds status, materials, height, width, length and weight fields to CatalogPart

---

ichub-backend/controllers/fastapi/app.py
ichub-backend/services/submodel_dispatcher_service.py

- Fixed bug on the metadata database models.
- Fixed bug on #193 
- Added submodel push api.
Some implementation where not done according to the requirements. I needed to improve the flexibility of the solution, otherwise if we keep adding functionality it will not be reachable.

Feat/sdk tutorial: added sdk tutorial requirements and fixed bugs

---

charts/industry-core-hub/Chart.yaml
charts/industry-core-hub/templates/configmap-backend.yaml
charts/industry-core-hub/values-int.yaml
charts/industry-core-hub/values.yaml
ichub-backend/config/configuration.yml
ichub-backend/controllers/fastapi/app.py
ichub-backend/managers/enablement_services/submodel_service_manager.py
ichub-backend/services/submodel_dispatcher_service.py

- Fixed helm charts
- Added delete method for submodels
It was required to delete the submodels we upload, so we can manage it.
It can or be managed by the user or done by the ichub.

Hotfix/submodels: Added Delete Method and Fixed Upload Method

---

ichub-backend/Dockerfile

_Briefly describe what your PR changes, which features it adds/modifies._
_Briefly state why the change was necessary._

fix: fixed docker file image generation

---

charts/industry-core-hub/Chart.yaml
charts/industry-core-hub/templates/configmap-backend.yaml
charts/industry-core-hub/templates/deployment-backend.yaml
charts/industry-core-hub/values.yaml

- Added dynamic volume configuration
- Untangled the unclear dependencies at the chart
It was necessary to fix the integrity for the E2E test phase when testing in a real kubernetes cloud environment it was failing.

feat: added new volume configuration

---

charts/industry-core-hub/values.yaml

- Added fix at volumes names which were not resolving
Because it was inconsistent 

feat added volumes fix

---

ichub-backend/controllers/fastapi/app.py
ichub-backend/controllers/fastapi/routers/__init__.py
ichub-backend/controllers/fastapi/routers/part_management.py
ichub-backend/controllers/fastapi/routers/partner_management.py
ichub-backend/controllers/fastapi/routers/sharing_handler.py
ichub-backend/controllers/fastapi/routers/submodel_dispatcher.py
ichub-backend/controllers/fastapi/routers/twin_management.py
ichub-backend/tools/submodel_type_util.py

- Added `/health`api
- Moved apis to different file routers to organize the Microservice modules
- Fixed bug related to semantic id which was failing on start up.
Right now how the apis are organized, they were ordered in a flat list, and needed to be reformed.

Feat/microservices: Refactored microservices fast api folder into sections with routers

---

DEPENDENCIES_ICHUB-FRONTEND
ichub-frontend/package-lock.json

- Fixed dependencies that had vulnerabilities `libxml2`
Because the trivy was failing we needed to fix the vulnerabilities.

feat: added new frotnend requirments + fixed vulnerabilities

---

charts/industry-core-hub/values-int.yaml

Adds CORS header to allow frontend requests to the backend. It also allows local testing with localhost:5137

chore: set CORS on INT values.yaml

---

DEPENDENCIES_ICHUB-FRONTEND
docs/database/Metadata-DDL-public.sql
ichub-backend/controllers/fastapi/routers/twin_management.py
ichub-backend/services/twin_management_service.py
ichub-frontend/index.html
ichub-frontend/package-lock.json
ichub-frontend/package.json
ichub-frontend/src/assets/styles/pages/_ProductDetail.scss
ichub-frontend/src/assets/styles/pages/_ProductList.scss
ichub-frontend/src/features/catalog-management/api.ts
ichub-frontend/src/features/catalog-management/components/product-detail/ProductData.tsx
ichub-frontend/src/features/catalog-management/components/product-detail/SharedTable.tsx
ichub-frontend/src/features/catalog-management/components/product-list/ProductCard.tsx
ichub-frontend/src/features/partner-management/components/general/CreateProductListDialog.tsx
ichub-frontend/src/pages/ProductsDetails.tsx
ichub-frontend/src/pages/ProductsList.tsx
ichub-frontend/src/services/EnvironmentService.ts
ichub-frontend/src/types/twin.ts

Adds a button to register catalog parts. Depending on the request response, it will show a snackbar with the response status. It also adds a tooltips in the CatalogCard icons.
Removes not required customer_part_ids from the create part dialog.

feat: Adds register button for catalog parts

---

deployment/data-consumer/Chart.yaml
deployment/data-consumer/values-int.yaml
deployment/data-provider/Chart.yaml
deployment/data-provider/values-int.yaml
deployment/data-provider/values.yaml

Added new edc configuration for R25.06, for testing
It is required to pass the release E2E test phase

feat/edc-dtr-r25.06: new edc 0.10.0 configuration & dtr 0.8.0

---

ichub-backend/controllers/fastapi/app.py
ichub-backend/controllers/fastapi/routers/part_management.py
ichub-backend/controllers/fastapi/routers/partner_management.py
ichub-backend/controllers/fastapi/routers/sharing_handler.py
ichub-backend/controllers/fastapi/routers/submodel_dispatcher.py
ichub-backend/controllers/fastapi/routers/twin_management.py
ichub-backend/managers/enablement_services/__init__.py
ichub-backend/managers/enablement_services/connector_manager.py
ichub-backend/managers/enablement_services/dtr_manager.py
ichub-backend/managers/enablement_services/submodel_service_manager.py
ichub-backend/managers/submodels/submodel_document_generator.py
ichub-backend/services/part_management_service.py
ichub-backend/services/sharing_service.py
ichub-backend/services/submodel_dispatcher_service.py
ichub-backend/services/twin_management_service.py
ichub-backend/tools/__init__.py
ichub-backend/tools/exceptions.py
ichub-backend/tools/submodel_type_util.py

- Centralized all exception handling
- Created an `ErrorDetail` model to standardize error responses
- Documented possible exception responses in Swagge
To improve the ICHUB error handling consistency and API documentation
Closes #255

feat: Improve the error and exception handling in the ichub

---

ichub-backend/controllers/fastapi/routers/part_management.py
ichub-backend/models/services/part_management.py
ichub-backend/services/part_management_service.py

Introduce a new API endpoint to create a mapping for customer part IDs associated with existing catalog parts, enhancing the part management functionality.
Based on PR #274

feat: Add API operation for customer part ID mapping in catalog part

---

ichub-backend/controllers/fastapi/routers/twin_management.py
ichub-backend/models/services/twin_management.py
ichub-backend/services/sharing_service.py
ichub-backend/services/twin_management_service.py

Added a share operation for serialized parts.

Implement share operation for serialized parts
