eclipse-tractusx/industry-core-hub

ichub-backend/main.py, tractusx_sdk/dataspace/main.py, tractusx_sdk/industry/main.py
Initialize the `authManager` in the `start` method in all three components: `ichub-backend`, `dataspace` and `industry`
Without this initialization, the three components cannot perform the authentication step and will fail when querying.
Closes #27
=> fix: ensure authManager is properly initialized to avoid missing 'self' error

.github/workflows/codeql.yml
Add the CodeQL workflow.
Use [CodeQL](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-01/) for deep, static code analysis to identify vulnerabilities and improve code quality across a wide range of programming languages.
Related to #2
=> feat: Add security TRG CodeQL 

ichub-backend/main.py, ichub-backend/requirements.txt, ichub-backend/tests/test_main.py, pytest.ini, test.sh, tractusx_sdk/dataspace/main.py, tractusx_sdk/dataspace/requirements.txt, tractusx_sdk/dataspace/tests/test_main.py, tractusx_sdk/industry/main.py, tractusx_sdk/industry/requirements.txt, tractusx_sdk/industry/tests/test_main.py, tractusx_sdk/shared/tests/manager/__init__.py, tractusx_sdk/shared/tests/manager/test_auth_manager.py
- Added `pytest` and `httpx` as a new testing frameworks to complement `unittest` for project testing.
- Implemented tests for `AuthManager` and the `/example` endpoints to verify that the initial configuration works as expected.
Ensures that the new frameworks pass the `DEPENDENCY-CHECK`.
Refers to #29
=> feat: Integrate pytest and httpx as a new test framework alongside unittest

.github/workflows/trivy.yml
Add the Trivy workflow.
[Trivy](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-04/) scans our Docker containers to accurately identify and remediate vulnerabilities in OS packages and application dependencies, ensuring our environment remains secure.
Related to #2
=> feat: Add security TRG Trivy

.github/workflows/kics.yaml
Add the KICS workflow.
[KICS](https://eclipse-tractusx.github.io/docs/release/trg-8/trg-8-02/) is deployed for comprehensive scanning of Infrastructure as Code (IaC) files, ensuring secure and best-practice configurations across various IaC frameworks.
Related to #2
=> feat: Add security TRG KICS

.github/workflows/codeql.yml, ichub-backend/services/__init__.py
I have tested this change in my repository and works fine when executes checks.
I have changed that the GH Actions only executes when there are codes changed being made, so that it doesn't gives as an error when other types of files.
=> fix: Update codeql.yml for checks in GH Action

ichub-backend/models/example_drx.py
Added a sample database model for discussion. It is based on the ideas and concepts implemented in DRÄXLMAIER's own industry core solution.
- [ x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files
=> feat: Added sample database model based on DRÄXLMAIER implementation

.github/workflows/dependencies-frontend.yaml
Adds a workflow to run the eclipse dash license checker each time frontend dependencies are updated.
Similar to #51
Related to #2 
Based in the portal-frontend workflow: https://github.com/eclipse-tractusx/portal-frontend/blob/main/.github/workflows/dependencies.yaml
=> feat: add frontend dependencies check workflow

deployment/data-consumer/.helmignore, deployment/data-consumer/Chart.yaml, deployment/data-consumer/README.md, deployment/data-consumer/templates/_helpers.tpl, deployment/data-consumer/templates/post-install-vault-setup.yaml, deployment/data-consumer/templates/vault-edc-configmap.yaml, deployment/data-consumer/values-int-vault.yaml, deployment/data-consumer/values-int.yaml, deployment/data-consumer/values.yaml, deployment/data-provider/.helmignore, deployment/data-provider/Chart.yaml, deployment/data-provider/README.md, deployment/data-provider/templates/_helpers.tpl, deployment/data-provider/templates/post-install-vault-setup.yaml, deployment/data-provider/templates/vault-edc-configmap.yaml, deployment/data-provider/values-int-vault.yaml, deployment/data-provider/values-int.yaml, deployment/data-provider/values.yaml
I wanted to provide an example on how could we deploy our EDCs to be able to develop our applications against it.
From the data provider perspective it was also provided a DTR and a Data Storage Service.
=> Helm Charts for Data Provision and Data Consumption infrastructure, with DTR, 2x EDCs, Data Storage Service

charts/industry-core-hub/README.md, charts/industry-core-hub/templates/_helpers.tpl, charts/industry-core-hub/templates/deployment-backend.yaml, charts/industry-core-hub/values.yaml
This pull request introduces an environment variable to the backend deployment that contains a PostgreSQL connection string. Additionally, it adds support for modifying the preferred sslMode for the PostgreSQL connection.
As part of this update, the old environment variables DATABASE_HOST, DATABASE_USER, and DATABASE_PORT have been removed, as their values are now incorporated into the connection string. This connection string will serve as the primary method for establishing a connection to the database.
It must be merged before: #132 
=> chore(helm): add Postgres DSN connection string

charts/industry-core-hub/templates/_helpers.tpl
This pull request includes a change to the `charts/industry-core-hub/templates/_helpers.tpl` file to correctly reference the PostgreSQL host. The modification ensures that the correct fullname template is used when PostgreSQL is enabled.
Fixed URL:
The bug was introduced in #150 
=> fix(helm-chart): update PostgreSQL host definition to use fullname

charts/industry-core-hub/values.yaml
Frontend deployment memory resource didn't match request and limit, so it wasn't compliant with TRG 5.04.
https://eclipse-tractusx.github.io/sig-release/
=> fix(TRG 5.04): match memory request and limit for frontend

charts/industry-core-hub/templates/_helpers.tpl, charts/industry-core-hub/templates/deployment-backend.yaml, charts/industry-core-hub/templates/deployment-frontend.yaml, charts/industry-core-hub/templates/pvc-data-backend.yaml, charts/industry-core-hub/templates/secret-backend-postgres.yaml, charts/industry-core-hub/templates/service-backend.yaml, charts/industry-core-hub/templates/service-frontend.yaml
This pull request includes changes to the Helm chart templates for the `industry-core-hub` to improve label management by introducing separate label definitions for backend and frontend components. 
Previously, both backend and frontend were using the same labels, which can be problematic for selector labels and could confuse Kubernetes.
=> fix: separate backend and frontend labels in Helm templates

.github/workflows/docker-build.yml
Add additional option to dispatch docker release workflow manually
=> chore(docker): add workflow_dispatch option for docker release

.github/workflows/verify.yml
#162 introduced docker notice files for the docker images, these files can't include license notice like other .md files, so I have added an exclusion tag in the verification workflow.
=> fix(license-verification): update license header verification to exclude docker notice files

DEPENDENCIES_ICHUB-BACKEND, ichub-backend/requirements.txt
Update the TractusX-SDK to the latest version.
=> chore: bump TractusX-SDK version

.github/workflows/helm-test.yaml, charts/industry-core-hub/Chart.yaml, charts/industry-core-hub/README.md, charts/industry-core-hub/values.yaml
Now that we have the 0.0.1 tag on dockerhub I have updated the chart to use the released images. This pr will publish the first helm chart version 0.1.3 with the 0.0.1 appVersion.
It also updates the helm test workflow, which was relying on manually built images. To use released images.
=> Chore: set dockerhub as repo in helm chart

.github/workflows/verify.yml
Exclude the `.github` directory from License file verification.
The workflow currently fails due to the PR template in that directory.
=> fix: exclude .github folder from Verify MD license check

.github/workflows/helm-test.yaml
Now that we have a released Helm chart, this PR includes in the helm-test workflow the upgradability check required by TRG 5.11
Required by [TRG 5.11](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11/)
=> chore: Update helm-test.yaml to include upgrade step (TRG 5.11)

INSTALL.md, README.md
Adds installation guide for ICHUB. INSTALL.md
Required by [TRG 1.02](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2)
Closes #216
=> docs(TRG 1.02): Add installation guide for Industry Core Hub

ichub-frontend/src/assets/styles/pages/_PartnersList.scss, ichub-frontend/src/assets/styles/pages/_ProductList.scss, ichub-frontend/src/components/general/LoadingSpinner.tsx, ichub-frontend/src/features/catalog-management/components/product-list/ProductCard.tsx, ichub-frontend/src/pages/ProductsDetails.tsx, ichub-frontend/src/pages/ProductsList.tsx
The new error message to display when there are no catalog parts, was displayed one second before the list was loaded (the time it took for the API to respond). To avoid this problem, an `isLoading`  state has been included, to show a loading spinner while loading and thus show the error message only when the list is empty.
Take into account that now, the API is really fast to respond, so the loading state is almost nothing in a matter of time. However, this is important because if the API would take longer to load, the error message would be displayed without any error.
=> Fix: Include loading spinner in catalog parts to not show error message

charts/industry-core-hub/Chart.yaml, charts/industry-core-hub/values.yaml, docs/admin/migration-guide.md
This PR updates the chart versions for several Helm charts and introduces a temporary workaround for PostgreSQL image configuration in the values.yaml files.
* Added explicit configuration for the PostgreSQL image repository and tag in `values.yaml` to use `bitnamilegacy/postgresql:15.4.0-debian-11-r45` as a workaround for compatibility until the team aligns on new PostgreSQL charts.
To ensure compatibility and deployment stability after the deprecation of the Bitnami image repository.
Closes #305
=> fix: replace bitnami repository by bitnamilegacy
